#' @title rearrange_cmdstan_samples_coalition_model
#' @description
#' Rearrange the samples from the coalition model so they can be used in the downstream code
#'
#' @param samples_cmdstan samples generated by cmdstan
#' @param model_data_list list of model data containing entries for K1, K2, K3, N_new
#' @return list of rearranged samples
#' @export
# nolint start
rearrange_cmdstan_samples_coalition_model <-
  # nolint end
  function(samples_cmdstan, model_data_list) {
    K1_param <- model_data_list[["K1"]]
    beta_names <- paste0("beta[", 1:K1_param, "]")
    K2_param <- model_data_list[["K2"]]
    beta_parties_names <- paste0("beta_parties[", 1:K2_param, "]")
    K3_param <- model_data_list[["K3"]]
    beta_party_names <- paste0("beta_party[", 1:K3_param, "]")
    N_new_param <- model_data_list[["N_new"]]
    y_new_names <- paste0("y_new[", 1:N_new_param, "]")
    return(
      list(
        beta = as.matrix(samples_cmdstan[beta_names]),
        beta_parties = as.matrix(samples_cmdstan[beta_parties_names]),
        beta_party = as.matrix(samples_cmdstan[beta_party_names]),
        tau = samples_cmdstan$tau,
        nu = samples_cmdstan$nu,
        beta_afd = samples_cmdstan$beta_afd,
        y_new = as.matrix(samples_cmdstan[y_new_names] %>% select(y_new_names))
      )
    )
  }
